// =============================================================================
// The `info.description` Markdown shown at the top of /api/docs (issue #53)
// =============================================================================
//
// This is the getting-started guide. It is baked into the OpenAPI document
// rather than written on a separate page so that it travels with the spec:
// anyone who downloads `/api/openapi.json`, imports it into Postman, or
// generates an SDK from it gets the same orientation the docs page shows.
//
// Keep it task-shaped (how do I get a token, what does a response look like,
// how do I page) rather than a feature tour — the tag sections below it are the
// feature tour. And keep it TRUE: everything here is checked against the
// running code, because a getting-started guide that lies costs more than one
// that is missing.
// =============================================================================

/**
 * Builds the Markdown intro.
 *
 * @param version resolved application version, echoed so a reader can tell
 *   which build they are pointed at without cross-checking `info.version`.
 */
export function buildApiDescription(version: string): string {
  return `
The HTTP API behind **OPIFEX** — a production-grade application base with Google
OAuth sign-in, role- and permission-based authorization, per-user and system
settings, object storage, and an email allowlist gating who may sign in at all.

This page is generated from the running server (build \`${version}\`), so it always matches the
deployment you are pointed at. The machine-readable document is at
[\`/api/openapi.json\`](/api/openapi.json).

---

## Getting a token

Authentication is applied per route. Every operation below states which credentials it
accepts; an operation with no security requirement listed needs none (the health probes and
the sign-in routes themselves).

There are three ways to obtain a bearer token, in rough order of how often you will want each.

### 1. Your browser session (fastest, for exploring these docs)

If you are already signed in to this deployment in this browser, press **Authorize with my
session** at the top of this page. It calls \`POST /api/auth/refresh\` with your existing refresh
cookie and loads the returned access token into the client below. Nothing to copy or paste, and
the authorization survives a reload.

Access tokens are short-lived (15 minutes by default). If calls start returning \`401\`, press the
button again.

### 2. Personal access token — scripts and automation

Mint a \`pat_…\` token via \`POST /api/pat\` and send it as \`Authorization: Bearer pat_…\`. The
authentication guard recognizes the \`pat_\` prefix before it ever reaches JWT verification, so a
PAT is accepted on **every** authenticated route in this document — there is no narrower scope.
It resolves to the full role and permission set of the user that minted it, which is why it should
be treated exactly like that user's password. Revoke with \`DELETE /api/pat/{id}\`.

### 3. Device authorization grant — CLI and other browserless clients

For a machine that cannot open a browser, use the RFC 8628 flow: \`POST /api/auth/device/code\`
to get a user code, show it to the user, and poll \`POST /api/auth/device/token\` until they
approve it at the activation page. Sessions created this way are listed and revocable under
**Device Authorization**.

Note that sign-in of any kind is gated by the email allowlist: an address an administrator has
not added cannot complete OAuth at all, regardless of which flow it uses.

---

## Response shape

A global response interceptor wraps every successful JSON body in a \`data\` envelope, adding a
sibling \`meta\` carrying the server timestamp:

\`\`\`json
{
  "data": { "id": "…", "email": "…" },
  "meta": { "timestamp": "2026-08-17T04:37:58.000Z" }
}
\`\`\`

The one exception is a handler that already returns an object with a \`data\` key — the interceptor
passes those through untouched, so they get no \`meta\`. The response schema shown for each
operation is authoritative; it is generated by applying that same rule to the document.

### Paginated lists

Every list endpoint is offset-paginated with \`page\` and \`pageSize\` query parameters, but there
are **two different body shapes**, and a client that consumes more than one list will hit both:

- **Flat** — \`GET /api/users\`, \`GET /api/allowlist\`. Counts sit beside \`items\`:

  \`\`\`json
  { "data": { "items": [ … ], "total": 42, "page": 1, "pageSize": 20, "totalPages": 3 } }
  \`\`\`

- **Nested** — \`GET /api/storage/objects\`. Counts sit in a \`meta\` object *inside* \`data\`, and
  the total is named \`totalItems\` rather than \`total\`:

  \`\`\`json
  { "data": { "items": [ … ], "meta": { "page": 1, "pageSize": 20, "totalItems": 42, "totalPages": 3 } } }
  \`\`\`

Note also that the inner \`meta\` of a nested list is a different object from the envelope's own
\`meta\`, which holds the timestamp. This asymmetry is a known defect, tracked separately; it is
documented here rather than quietly smoothed over because the wire format is what it is today and
a client has to handle both.

---

## Errors

Every error passes through one exception filter, which rebuilds the body from a fixed key
allowlist. These six keys are the complete set — nothing else can appear:

\`\`\`json
{
  "statusCode": 409,
  "code": "CONFLICT",
  "message": "Email already in allowlist",
  "details": { "field": "email" },
  "timestamp": "2026-08-17T04:37:58.000Z",
  "path": "/api/allowlist"
}
\`\`\`

\`details\` is present only when the failure carried structured data, and it is the **only** place
endpoint-specific data survives: a custom top-level field on a thrown exception is dropped before
it reaches you. \`code\` is derived from the status by the filter and overrides anything the thrown
exception set, so it is always one of the values enumerated on \`ErrorDto\` — branch on it rather
than on \`message\`, which is prose.

Errors are **not** wrapped in the \`data\` envelope: the filter writes straight to the reply and
bypasses the response interceptor.

---

## Permissions

Authorization is a single layer. A user holds one or more **system roles** — \`admin\`,
\`contributor\`, \`viewer\` — and each role grants a set of **permissions** named \`resource:action\`
(\`users:read\`, \`system_settings:write\`, \`storage:delete_any\`, \`rbac:manage\`).

Guarded operations state their requirements in a generated **Requires:** line. Where several
roles are listed the guard admits any one of them; where several permissions are listed the guard
requires all of them. Those lines are rendered from the same \`@Auth()\` metadata the guards read,
so they cannot drift from what the server enforces.

Deactivated users are rejected at authentication time regardless of their roles.

---

## Conventions

- All timestamps are ISO 8601 in UTC.
- All ids are UUIDs unless documented otherwise.
- Object sizes are returned as **strings**, not numbers — they are 64-bit values that would lose
  precision as JSON numbers.
- \`204 No Content\` responses have no body, and are therefore not enveloped.
- The API is served same-origin under \`/api\`; this document's server is \`/\`.

## Further reading

Architecture, security and operations documentation lives in the repository under
[\`docs/\`](https://github.com/marinoscar/opifex/tree/main/docs).
`.trim();
}
